import { NextResponse } from "next/server";
import {
  applyEnrichmentToProduct,
  buildFallbackProductFromProduct,
  buildOptimizationMeta,
  buildProductInsight,
  normalizeEnrichment,
  summarizeCatalog
} from "@/lib/scoring";
import { getWorkspace, recordOptimization } from "@/lib/server-store";
import type { EnrichedContent, Product } from "@/lib/types";

export async function GET() {
  const workspace = await getWorkspace();
  return NextResponse.json({
    summary: summarizeCatalog(workspace.products),
    products: workspace.products.map(buildProductInsight),
    optimizationRuns: workspace.optimizationRuns
  });
}

export async function POST(request: Request) {
  const body = (await request.json()) as { product?: Product };
  const product = body.product;

  if (!product) {
    return NextResponse.json({ error: "Missing product payload." }, { status: 400 });
  }

  const fallbackProduct = buildFallbackProductFromProduct(product);
  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_MODEL ?? "gpt-5-mini";

  if (!apiKey) {
    const meta = buildOptimizationMeta(
      "fallback",
      "OPENAI_API_KEY is not set, so AgentShelf used the built-in optimization logic."
    );
    await recordOptimization(fallbackProduct, meta);
    return NextResponse.json({ product: fallbackProduct, meta });
  }

  try {
    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model,
        input: [
          {
            role: "system",
            content: [
              {
                type: "input_text",
                text:
                  "You are AgentShelf, an AI commerce content optimizer. Convert a raw product listing into structured, recommendation-ready product knowledge for an AI shopping assistant. Use only grounded claims from the source listing. If a detail is uncertain, either omit it or list it in missingSignals."
              }
            ]
          },
          {
            role: "user",
            content: [
              {
                type: "input_text",
                text: JSON.stringify({
                  name: product.name,
                  brand: product.brand,
                  category: product.category,
                  price: product.price,
                  climate: product.climate,
                  fit: product.fit,
                  cushioning: product.cushioning,
                  rawDescription: product.rawDescription,
                  rawBullets: product.rawBullets,
                  currentGaps: product.gaps
                })
              }
            ]
          }
        ],
        text: {
          format: {
            type: "json_object"
          }
        }
      })
    });

    if (!response.ok) {
      throw new Error(`OpenAI request failed with status ${response.status}`);
    }

    const payload = (await response.json()) as { output_text?: string };
    const parsed = JSON.parse(payload.output_text ?? "{}") as Partial<EnrichedContent>;
    const enriched = normalizeEnrichment(parsed, fallbackProduct);
    const optimizedProduct = applyEnrichmentToProduct(fallbackProduct, enriched);

    const meta = buildOptimizationMeta(
      "openai",
      "Optimization was generated by a live OpenAI model and then rescored by AgentShelf.",
      model
    );
    await recordOptimization(optimizedProduct, meta);
    return NextResponse.json({ product: optimizedProduct, meta });
  } catch (error) {
    const meta = buildOptimizationMeta(
      "fallback",
      `Live enrichment failed, so AgentShelf used the built-in optimizer instead: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
    await recordOptimization(fallbackProduct, meta);
    return NextResponse.json({ product: fallbackProduct, meta });
  }
}
